project:
  type: website
  output-dir: docs
website:
  title: "Mario"
  search: true
  site-url: https://aayushmnit.github.io/quarto_example/
  repo-url: https://github.com/aayushmnit/quarto_example
  navbar:
    left:
      - icon: house
        href: index.qmd
        text: Home
      - icon: file-person
        href: about.qmd
        text: About
      - icon: newspaper
        href: blog.qmd
        text: Blogs

    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/
      - icon: linkedin
        href: https://linkedin.com/
format:
  html:
    theme: 
      light : cosmo
      dark : cyborg
    css: styles.css
    toc: true



